--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.8) ~  Much Love, Ferib 

]]--

local v0=require("gamesense/http");local v1=require("json");local v2=require("gamesense/base64");local v3={};local v4=0;print("loader started sucess");local function v5() return os.time();end local function v6(v16) v0.get(v16,function(v22,v23) if (v22 and (v23.status==(1090 -(668 + 222)))) then local v26,v27=load(v23.body);if v26 then local v30,v31=pcall(v26);if v30 then print("Lua loaded and executed successfully.");else print("Error executing Lua: "   .. v31 );end else print("Error loading Lua from: "   .. v16   .. " - "   .. v27 );end else print("Failed to download Lua. Status: "   .. v23.status );end end);end local function v7(v17) if v3[v17] then local v25=0;while true do if (v25==(0 + 0)) then v3[v17]=nil;print(v17   .. " Lua unloaded successfully." );v25=878 -(282 + 595) ;end if (v25==1) then client.reload_active_scripts();print("Active scripts reloaded.");v25=1639 -(1523 + 114) ;end if (v25==(2 + 0)) then client.exec("play music/3kliksphilip_01/mainmenu");break;end end else print("No Lua to unload for "   .. v17 );end end local v8={"\a7AFF67FF • \aFFFFFFFFCalamity beta"};local v9={["\a7AFF67FF • \aFFFFFFFFCalamity beta"]="https://raw.githubusercontent.com/Slowdex1337/calamity/refs/heads/main/calamity.lua"};local v10=panorama.open("CSGOHud").MyPersonaAPI.GetName();local v11=ui.new_listbox("LUA","B"," ",table.unpack(v8));local function v12() local v18=0 -0 ;local v19;local v20;local v21;while true do if (v18==(1066 -(68 + 997))) then v21=v9[v20];if v21 then if v3[v20] then v7(v20);else v6(v21);v3[v20]=true;client.exec("play buttons/button3");end else print("Invalid Lua selection.");end break;end if (v18==(1270 -(226 + 1044))) then v19=ui.get(v11) + (4 -3) ;v20=v8[v19];v18=118 -(32 + 85) ;end end end local v13=ui.new_button("LUA","B","\aA9A9A9FFLoad \aA9A9A9FF/ \aA9A9A9FFUnload ",v12);local v14=ui.new_label("LUA","B","\aFFFFFFFFUser : \a75AB6FFF"   .. v10 );client.set_event_callback("shutdown",function() for v24 in pairs(v3) do v7(v24);end end);local function v15() v4=v4 + 1 ;end client.set_event_callback("on_timer",function() v15();      end);
